---
title: "20220213_NLP-AleCav_Gissela-Cornejo"
author: "Gissela_Cornejo_Castellano"
date: "7/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Librerías}
library(rtweet)
library(tidyverse)
library(twitteR)
library(ROAuth)
library(httr)
library(tm)
library(SnowballC)
library(base64enc)
library(jsonlite)
```
```{r}
require(httr)
require(jsonlite)
require(dplyr)
```

```{r}
bearer_token <- Sys.getenv("AAAAAAAAAAAAAAAAAAAAABbTYwEAAAAArNICJ5uq1dwShJnC1tkwPH6Fr0c%3DbBpY2uchEP9zcUXIAPs7QAUvbXmZyEds5akiXnbIxjyAEBIGoZ")
headers <- c(`Authorization` = sprintf('Bearer %s', bearer_token))
```

```{r}
params <- list(`user.fields` = 'text')
```

```{r}
handle <- readline('@AlejandroCavero')
url_handle <-
  sprintf('https://api.twitter.com/2/users/by?@AlejandroCavero=%s', handle)
```

```{r}
response <-
  httr::GET(url = url_handle,
            httr::add_headers(.headers = headers),
            query = params)
obj <- httr::content(response, as = "text")
print(obj)
```

```{r}
json_data <- fromJSON(obj, flatten = TRUE) %>% as.data.frame
View(json_data)
```

```{r}
final <-
  sprintf(
    "Handle: %s\nBio: %s\nPinned Tweet: %s",
    json_data$data.username,
    json_data$data.description,
    json_data$includes.tweets.text
  )
```

```{r}
cat(final)
```


```{#r}
api_key <- "K2pviSkiv84wO7Pnk7IJOcoiw"
api_secret <- "qfcfxdpvduTQz170CVgtW1krIOSIlLYLbNSlYZM5lubRxsTVeq"
access_token <- "814222538440134657-DlkjGkZqQuCng4ryXlvogShIbQB0jXd"
access_token_secret <- "4XwJH8VwpG2N9dghqHMaIpptyFTrdQNFWx31U3NYUI0Uh"

token <- create_token(
  app = "R_pc2",
  consumer_key = api_key,
  consumer_secret = api_secret,
  access_token = access_token,
  access_secret = access_token_secret)

token
```


```{#r}
consumer_key = api_key
consumer_secret = api_secret
access_token = access_token
access_secret = access_token_secret

setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
```

```{#r}
set_bearer()
```

```{#r}

tweets <-
  get_all_tweets(
    query = "@AlejandroCavero",
    start_tweets = "2021-07-28T00:00:00Z",
    end_tweets = "2020-02-07T00:00:00Z",
    file = "caverotweets",
    data_path = "data/",
    n = 1000,
  )
  
```

